apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hwwp7ogj2-dotnet-basic 
  janus-idp.io/tekton: hwwp7ogj2-dotnet-basic
  backstage.io/kubernetes-id: hwwp7ogj2-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hwwp7ogj2-dotnet-basic
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml